piVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: infra-pd-inference-gateway
  labels:
    istio.io/enable-inference-extproc: "true"
  annotations:
    networking.istio.io/service-type: ClusterIP # TODO: should we use clusterIP of lob(as set in CM)
spec:
  gatewayClassName: "istio" # refer to the GWC created in 'prereq' stage
  infrastructure:
    parametersRef:
      name: infra-pd-inference-gateway
      group: ""
      kind: ConfigMap
