apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - decode.yaml
  - prefill.yaml
  - serviceAccount.yaml

labels:
  - pairs:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: Llama-33-70B-Instruct
