name: CI - PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.1

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Install hadolint
        run: |
          wget -O /usr/local/bin/hadolint \
            https://github.com/hadolint/hadolint/releases/download/v2.14.0/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.12'

      - name: Run pre-commit
        uses: j178/prek-action@v1
        with:
          extra-args: ''

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.1

      - name: warning about ignored paths
        run: |
          echo "Warning! Some paths are ignored in the markdown link checker config.
          This is because those websites have strong anti-scraping behaviours. For
          the full list of ignored paths, see the lychee.toml file:"
          cat lychee.toml

      - name: Run markdown link checker
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          args: --verbose --no-progress --format markdown '**/*.md'
          fail: true
