name: Re-Run PR tests

on:
  issue_comment:
    types: [created]

jobs:
  rerun_pr_tests:
    name: rerun_pr_tests
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-24.04
    steps:
      - name: Re-run PR tests
        uses: estroz/rerun-actions@v0.3.0  # current latest commit on main has no function change since 0.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          comment_id: ${{ github.event.comment.id }}
